### ISSUE TITLE
Expose the Loc module

### ISSUE THREAD

**Issue by mjambon** [diml/dune-file#1]
I wrote the following code, which works fine:

```ocaml
    try
      Dune_files.Parser.load path ~mode:Many
      |> List.map Dune_files.Ast.remove_locs
    with
    | Dune_files.Lexer.Parse_error (loc, msg) ->
        let msg =
          sprintf "%s\n%s"
            (Dune_files__Loc.to_human_readable_location loc)
            msg
        in
        failwith msg
```

However, it references `Dune_files__Loc`, which is permitted but looks wrong. I suggest adding `Loc` to `dune_files.ml` so we can reference it as `Dune_files.Loc`.

**Comment by diml** [comment]
That seems good indeed, I did that
