### ISSUE TITLE
This character is not allowed inside %{...} forms

### ISSUE THREAD

**Issue by mjambon** [diml/dune-file#4]
With the dev version of dune-deps (`parsing` branch) which uses `dune-files` since today, we're getting the following error:
```
$ dune-deps dune
Error: File "dune/test/blackbox-tests/test-cases/quoting/filename-space/dune", line 4, characters 17-18:
This character is not allowed inside %{...} forms
```
The file contents are:
```

(alias
 (name unquoted)
 (action (echo %{read:foo bar.txt})))

(alias
 (name quoted)
 (action (echo "%{read:foo bar.txt}")))
```
The error location is on the `r` of `read` in the first `(action (echo %{read:foo bar.txt})))`.

**Comment by mjambon** [comment]
More specifically, the cause is due to the whitespace in the part following the colon. It appears to be the object of that specific test. I used the latest master branch of the dune repo.

This works fine:
```ocaml
Dune_files.Parser.parse_string ~fname:"string" ~mode:Many {|(%{read:foo})|};;
```
This fails:
```ocaml
# Dune_files.Parser.parse_string ~fname:"string" ~mode:Many {|(%{read:fo o})|};;
Exception:
Dune_files__Lexer.Parse_error
 ({Dune_files__.Loc.start =
    {Lexing.pos_fname = "string"; pos_lnum = 1; pos_bol = 0; pos_cnum = 3};
   stop =
    {Lexing.pos_fname = "string"; pos_lnum = 1; pos_bol = 0; pos_cnum = 4}},
 "This character is not allowed inside %{...} forms").
```

**Comment by diml** [comment]
Yeah, that's expected indeed.  There is a stanza `(data_only_dirs test-cases)` in `test/blackbox-tests/dune` which instructs dune not to interpret `dune` files under `test-cases`.

**Comment by mjambon** [comment]
Great. Sorry I didn't look very closely.

I don't think dune-deps should bother interpreting those exclusion stanzas at this point. Maybe when it becomes wildly popular or someone wants to pay for it.
